# Generated by Django 6.0.6 on 2026-07-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_alter_userprofile_refund_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Successful', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='Transfer', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], default='CREDIT', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
