from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('loginview/', views.loginview, name='loginview'),
    path('register/', views.register, name='reg'),
    path('account_frozen_page/', views.account_frozen_page, name='account_frozen_page'),
    path('reset_profile/', views.reset_profile, name='reset_profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('investment/plans/', views.investment_plans, name='investment_plans'),
    path('investment/create/', views.create_investment, name='create_investment'),
    path('investment/dashboard/', views.investment_dashboard, name='investment_dashboard'),
    path('investment/detail/<int:investment_id>/', views.investment_detail, name='investment_detail'),
    path('setting/', views.setting, name='setting'),
    path('transactionPage/', views.transactionPage, name='transaction'),
    path('bank/', views.bank, name='bank'),
    path('crypto/', views.crypto, name='crypto'),
    path('Upgrade_Account/', views.Upgrade_Account, name='Upgrade_Account'),
    path('paypal/', views.paypal, name='paypal'),
    path('skrill/', views.skrill, name='skrill'),
    path('kyc/', views.kyc, name='kyc'),
    path('pendingPro/', views.pendingPro, name='pendingPro'),
    path('loans/', views.loans, name='loans'),
    path('pending/', views.pending, name='pending'),
    path('Upgrade_Account/', views.Upgrade_Account, name='Upgrade_Account'),
    path('imf/', views.imf, name='imf'),
    path('bic/', views.bic, name='bic'),
    path('tax/', views.tax, name='tax'),
    path('G_pay/', views.G_pay, name='G_pay'),
    path('payoneer/', views.payoneer, name='payoneer'),
    path('western_union/', views.western_union, name='western_union'),
    path('trust_wise/', views.trust_wise, name='trust_wise'),
    path('linking_view/', views.linking_view, name='linking_view'),
    path('LogoutPage/', views.LogoutPage, name='logout'),
    path('apply-card/', views.application_for_credit_card, name='application_for_credit_card'),
    path('card-list/', views.card_list, name='card_list'),
    path('transaction/<int:pk>/', views.transaction_detail, name='transaction_detail'),
    path('test-email-status/', views.test_email_status, name='test_email_status'),
]
